version: '3.7'

services:
  nb:
    build: .
    ports:
      - "8888:8888"
    volumes:
      # 'cache' packages etc. in a named volume
      # (NOTE: not a bind mount (host directory) since it's super slow on macOS and 'delegated' does NOT help)
      - dot-julia:/root/.julia
      - .:/code
      - .container-bash-history:/root/.bash_history:delegated
    command: jupyter lab --ip=0.0.0.0 --allow-root
volumes:
  dot-julia:
